### ISSUE TITLE
fab render-notebooks fails with TypeError: invalid file

### ISSUE THREAD

**Issue by ngulden** [knowsuchagency/hugo_jupyter#3]
* Hugo Jupyter version: 0.2.1
* Python version: 3.5.2
* Operating System: Ubuntu 16.04 LTS

### Description

As described in the documentation, I initialized the hugo jupyter path and placed a notebook in there. The command `fab serve` calls the browser and I can select the notebook and make the necessary changes to add the front-matter. This notebook can also be run.

I want to render the notebook to be part of my hugo content. This fails.

### What I Did

```
$ fab render_notebooks
Traceback (most recent call last):
  File "/home/user/.virtualenvs/hugo_jupyter/lib/python3.5/site-packages/fabric/main.py", line 762, in main
    *args, **kwargs
  File "/home/user/.virtualenvs/hugo_jupyter/lib/python3.5/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/user/.virtualenvs/hugo_jupyter/lib/python3.5/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/home/user/src/jupyiter/fabfile.py", line 32, in render_notebooks
    write_jupyter_to_md(notebook)
  File "/home/user/src/jupyiter/fabfile.py", line 176, in write_jupyter_to_md
    hugo_markdown = convert_notebook_to_hugo_markdown(notebook)
  File "/home/user/src/jupyiter/fabfile.py", line 156, in convert_notebook_to_hugo_markdown
    with open(Path(path)) as fp:
TypeError: invalid file: PosixPath('notebooks/Install_Codes.ipynb')
```

**Comment by knowsuchagency** [comment]
After researching this issue, it seems like this may be more of an idiosyncrasy between pathlib and certain OS's, rather than a hugo-jupyter error, so I'm going to close this issue, but pull-requests or other amplifying information are always helpful.
